apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::651228606979:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2RAGUOGQW9T6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::651228606979:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-25T19:38:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "781"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3a5c8ccc-1bf3-4e05-a5db-6e04eee9492b
